Fix: don't use BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_MEMORY_ERROR
BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_MEMORY_ERROR has been removed,
so don't use it in validate_map_value.

Fixes the following compilation error:

    /home/smarchi/src/babeltrace/src/plugins/common/param-validation/param-validation.c: In function ‘validate_map_value’:
    /home/smarchi/src/babeltrace/src/plugins/common/param-validation/param-validation.c:226:30: error: ‘BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_MEMORY_ERROR’ undeclared (first use in this function); did you mean ‘BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_INTERRUPTED’?
      if (foreach_entry_status == BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_MEMORY_ERROR) {
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  BT_VALUE_MAP_FOREACH_ENTRY_CONST_STATUS_INTERRUPTED

Change-Id: Idc4ed1b198bfa40c9b3ba9d9532d69795f893c90
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/2174
Reviewed-by: Francis Deslauriers <francis.deslauriers@efficios.com>