Fix: bt2: duplicate test name in _IntegerRangeTestCase
Flake8 reports:

    ./tests/bindings/python/bt2/test_integer_range_set.py:45:5: F811 redefinition of unused 'test_create_wrong_type_lower' from line 41

I think the issue is simply that the second instance should have `upper`
instead of `lower`.

Reported-by: flake8
Change-Id: Id03b801951b9ce64eb0264debdd8ed4c4e3a577e
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/2091