Fix: common: va_list type is implementation dependant
Issue
=====
BT_ASSERT(*args) happens to work on some library implementations because
the va_list type happens to be a pointer but this is not true with all
libraries. For example, compiling on arm64 results in the following
error:
  In file included from common.c:34:0:
  common.c: In function ‘bt_common_custom_vsnprintf’:
  ../include/babeltrace/assert-internal.h:42:7: error: wrong type
  argument to unary exclamation mark
     if (!(_cond)) {                                                \
       	 ^
  common.c:1524:2: note: in expansion of macro ‘BT_ASSERT’
    BT_ASSERT(*args);
    ^~~~~~~~~

Solution
========
Remove that BT_ASSERT() call as its intent is unclear anyway.

Drawback
========
None.

Signed-off-by: Francis Deslauriers <francis.deslauriers@efficios.com>
Change-Id: Iada5189ef4580e48caefed12835bfab7c23eaf73
Reviewed-on: https://review.lttng.org/c/babeltrace/+/1253
CI-Build: Jérémie Galarneau <jeremie.galarneau@efficios.com>
Reviewed-by: Michael Jeanson <mjeanson@efficios.com>
Reviewed-by: Jérémie Galarneau <jeremie.galarneau@efficios.com>