Missing define when not building with gcc
Error encountered:

../../../../../src/compat/bitfield.h:471:2: error: unknown type name ‘_BT_DIAG_IGNORE_TYPE_LIMITS’; did you mean ‘_BT_DIAG_IGNORE’?
  _BT_DIAG_IGNORE_TYPE_LIMITS     \
  ^
../../../../../src/compat/bitfield.h:535:2: note: in expansion of macro ‘_bt_bitfield_read_be’
  _bt_bitfield_read_be(ptr, unsigned char, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:473:3: note: in expansion of macro ‘bt_bitfield_read_be’
   bt_bitfield_read_be(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:472:2: error: conflicting types for ‘_is_signed_type’
  _is_signed_type = _bt_is_signed_type(__typeof__(_v));  \
  ^
../../../../../src/compat/bitfield.h:535:2: note: in expansion of macro ‘_bt_bitfield_read_be’
  _bt_bitfield_read_be(ptr, unsigned char, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:473:3: note: in expansion of macro ‘bt_bitfield_read_be’
   bt_bitfield_read_be(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:458:7: note: previous declaration of ‘_is_signed_type’ was here
  bool _is_signed_type;      \
       ^
../../../../../src/compat/bitfield.h:535:2: note: in expansion of macro ‘_bt_bitfield_read_be’
  _bt_bitfield_read_be(ptr, unsigned char, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:473:3: note: in expansion of macro ‘bt_bitfield_read_be’
   bt_bitfield_read_be(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:399:2: error: unknown type name ‘_BT_DIAG_IGNORE_TYPE_LIMITS’; did you mean ‘_BT_DIAG_IGNORE’?
  _BT_DIAG_IGNORE_TYPE_LIMITS     \
  ^
../../../../../src/compat/bitfield.h:532:2: note: in expansion of macro ‘_bt_bitfield_read_le’
  _bt_bitfield_read_le(ptr, type, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:476:3: note: in expansion of macro ‘bt_bitfield_read_le’
   bt_bitfield_read_le(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:400:2: error: conflicting types for ‘_is_signed_type’
  _is_signed_type = _bt_is_signed_type(__typeof__(_v));  \
  ^
../../../../../src/compat/bitfield.h:532:2: note: in expansion of macro ‘_bt_bitfield_read_le’
  _bt_bitfield_read_le(ptr, type, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:476:3: note: in expansion of macro ‘bt_bitfield_read_le’
   bt_bitfield_read_le(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:386:7: note: previous declaration of ‘_is_signed_type’ was here
  bool _is_signed_type;      \
       ^
../../../../../src/compat/bitfield.h:532:2: note: in expansion of macro ‘_bt_bitfield_read_le’
  _bt_bitfield_read_le(ptr, type, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:476:3: note: in expansion of macro ‘bt_bitfield_read_le’
   bt_bitfield_read_le(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
bfcr.c: In function ‘read_signed_bitfield’:
../../../../../src/compat/bitfield.h:471:2: error: unknown type name ‘_BT_DIAG_IGNORE_TYPE_LIMITS’; did you mean ‘_BT_DIAG_IGNORE’?
  _BT_DIAG_IGNORE_TYPE_LIMITS     \
  ^
../../../../../src/compat/bitfield.h:535:2: note: in expansion of macro ‘_bt_bitfield_read_be’
  _bt_bitfield_read_be(ptr, unsigned char, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:492:3: note: in expansion of macro ‘bt_bitfield_read_be’
   bt_bitfield_read_be(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:472:2: error: conflicting types for ‘_is_signed_type’
  _is_signed_type = _bt_is_signed_type(__typeof__(_v));  \
  ^
../../../../../src/compat/bitfield.h:535:2: note: in expansion of macro ‘_bt_bitfield_read_be’
  _bt_bitfield_read_be(ptr, unsigned char, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:492:3: note: in expansion of macro ‘bt_bitfield_read_be’
   bt_bitfield_read_be(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:458:7: note: previous declaration of ‘_is_signed_type’ was here
  bool _is_signed_type;      \
       ^
../../../../../src/compat/bitfield.h:535:2: note: in expansion of macro ‘_bt_bitfield_read_be’
  _bt_bitfield_read_be(ptr, unsigned char, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:492:3: note: in expansion of macro ‘bt_bitfield_read_be’
   bt_bitfield_read_be(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:399:2: error: unknown type name ‘_BT_DIAG_IGNORE_TYPE_LIMITS’; did you mean ‘_BT_DIAG_IGNORE’?
  _BT_DIAG_IGNORE_TYPE_LIMITS     \
  ^
../../../../../src/compat/bitfield.h:532:2: note: in expansion of macro ‘_bt_bitfield_read_le’
  _bt_bitfield_read_le(ptr, type, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:495:3: note: in expansion of macro ‘bt_bitfield_read_le’
   bt_bitfield_read_le(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:400:2: error: conflicting types for ‘_is_signed_type’
  _is_signed_type = _bt_is_signed_type(__typeof__(_v));  \
  ^
../../../../../src/compat/bitfield.h:532:2: note: in expansion of macro ‘_bt_bitfield_read_le’
  _bt_bitfield_read_le(ptr, type, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:495:3: note: in expansion of macro ‘bt_bitfield_read_le’
   bt_bitfield_read_le(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~
../../../../../src/compat/bitfield.h:386:7: note: previous declaration of ‘_is_signed_type’ was here
  bool _is_signed_type;      \
       ^
../../../../../src/compat/bitfield.h:532:2: note: in expansion of macro ‘_bt_bitfield_read_le’
  _bt_bitfield_read_le(ptr, type, start, length, vptr)
  ^~~~~~~~~~~~~~~~~~~~
bfcr.c:495:3: note: in expansion of macro ‘bt_bitfield_read_le’
   bt_bitfield_read_le(buf, uint8_t, at, field_size, v);
   ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Jonathan Rajotte <jonathan.rajotte-julien@efficios.com>
Change-Id: Ie9438e87c69f21ad4062b277d26ee09551ae4c97
Reviewed-on: https://review.lttng.org/c/babeltrace/+/1629
Reviewed-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>
Tested-by: jenkins <jenkins@lttng.org>