cli: append error cause when graph or query executor is canceled by user
Otherwise the CLI prints "unknown error" at the end. Now it prints:

    ERROR:    [Babeltrace CLI] (babeltrace2.c:2579)
      Graph was canceled by user.

Signed-off-by: Philippe Proulx <eeppeliteloop@gmail.com>
Change-Id: Ia910e91d75586e30bb017bd9332615891606c115
Reviewed-on: https://review.lttng.org/c/babeltrace/+/1659
Tested-by: jenkins <jenkins@lttng.org>