Fix -Wsuggest-attribute warnings
plan_skip_all unconditionally exits, so it can be marked as noreturn.

Fixes:

  CC       tap.lo
/home/smarchi/src/babeltrace/tests/utils/tap/tap.c: In function ‘plan_skip_all’:
/home/smarchi/src/babeltrace/tests/utils/tap/tap.c:231:1: error: function might be candidate for attribute ‘noreturn’ [-Werror=suggest-attribute=noreturn]
 plan_skip_all(const char *reason)
 ^~~~~~~~~~~~~

Change-Id: I740aa065c888c53a7be880a9e6e68e6f12b1d42d
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/2259
Tested-by: jenkins <jenkins@lttng.org>
Reviewed-by: Francis Deslauriers <francis.deslauriers@efficios.com>