tests: get rid of missing-field-initializers warning in test_bin_info.c
This is not super important, and the current code looks correct, but
clang produces this warning:

    /home/smarchi/src/babeltrace/tests/plugins/flt.lttng-utils.debug-info/test_bin_info.c:93:7:
    error: missing field 'short_name' initializer
    [-Werror,-Wmissing-field-initializers]
            {NULL}};

I'd like to have this warning enabled, since it can catch some
legitimate mistakes, so I thought it would be useful to change the code
to avoid having a warning.

Change-Id: Icb5d3227b87ba1bbf405cd320f13886bf313492f
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/2133
Tested-by: jenkins <jenkins@lttng.org>
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>