trimmer: use g_match_info_free instead of g_match_info_unref
The build fails with glib 2.22:

    trimmer.c: In function ‘compile_and_match’:
    trimmer.c:201:3: error: implicit declaration of function ‘g_match_info_unref’; did you mean ‘g_match_info_free’? [-Werror=implicit-function-declaration]
       g_match_info_unref(*match_info);
       ^~~~~~~~~~~~~~~~~~
       g_match_info_free

The g_match_info_unref function is only available from glib 2.30.  Use
g_match_info_free instead, which does the same for our use case.

Change-Id: I9357b9dd18501749e19481e9ef08ec9b01379ee6
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/1633
Tested-by: jenkins <jenkins@lttng.org>
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>