lib: remove includes from logging.h
Nothing in logging.h uses anything from those includes.

Removing them causes this failure in py-common.c:

  CC       py-common.lo
In file included from /home/smarchi/src/babeltrace/src/py-common/py-common.c:32:0:
/home/smarchi/src/babeltrace/src/py-common/py-common.h:44:18: error: unknown type name ‘bool’; did you mean ‘_Bool’?
   int log_level, bool chain);
                  ^~~~
                  _Bool

Doing this change revealed a few files that were using bool without
including stdbool.h, add the includes there.

Change-Id: Ica802312a21c2a28cfaa1011d0034f0d1f65594e
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/2241
Tested-by: jenkins <jenkins@lttng.org>
Reviewed-by: Francis Deslauriers <francis.deslauriers@efficios.com>