Fix: bt2: duplicate test name in test_field.py
Flake8 reports:

    ./tests/bindings/python/bt2/test_field.py:2170:5: F811 redefinition of unused 'test_has_field_prop_true' from line 2166
    ./tests/bindings/python/bt2/test_field.py:2178:5: F811 redefinition of unused 'test_bool_op_true' from line 2174

I think that in both cases, the second instance was meant to be renamed
to `_false`.

Reported-by: flake8
Change-Id: I8b3143bb3f86982e220a6b516f028fca9e6e24ab
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/2093