Fix: tests: live: listen on python < 3.5 needs backlog parameter
The backlog parameter is required on python version smaller then 3.5.

On sles12sp2:

 Traceback (most recent call last):
   File "/home/jenkins/workspace/babeltrace_master_slesbuild/arch/sles12sp2/build/std/conf/prod/src/babeltrace/tests/data/plugins/src.ctf.lttng-live/lttng_live_server.py", line 1447, in <module>
     args.port_filename, args.sessions, args.max_query_data_response_size
   File "/home/jenkins/workspace/babeltrace_master_slesbuild/arch/sles12sp2/build/std/conf/prod/src/babeltrace/tests/data/plugins/src.ctf.lttng-live/lttng_live_server.py", line 1232, in __init__
     self._listen()
   File "/home/jenkins/workspace/babeltrace_master_slesbuild/arch/sles12sp2/build/std/conf/prod/src/babeltrace/tests/data/plugins/src.ctf.lttng-live/lttng_live_server.py", line 1323, in _listen
     self._sock.listen()
 TypeError: listen() takes exactly one argument (0 given)

Signed-off-by: Jonathan Rajotte <jonathan.rajotte-julien@efficios.com>
Change-Id: Ib923beb9eadf929714b3270aaa7a57ff6c52407e
Reviewed-on: https://review.lttng.org/c/babeltrace/+/2096
Reviewed-by: Simon Marchi <simon.marchi@efficios.com>